// File: Register_32bit.v
// Generated by MyHDL 0.11
// Date: Sun Feb  7 18:09:05 2021


`timescale 1ns/10ps

module Register_32bit (
    clk,
    rst,
    load,
    par_in,
    par_out
);
// Simple 32-bit data register. It can load and reset.
// :param clk: Clock signal
// :param rst: Reset signal
// :param load: Load enable signal
// :param par_in: Parallel 32-bit input
// :param par_out: Parallel 32-bit output

input clk;
input rst;
input load;
input [31:0] par_in;
output [31:0] par_out;
reg [31:0] par_out;




always @(posedge clk, negedge rst) begin: REGISTER_32BIT_LOGIC
    if (rst == 0) begin
        par_out <= 0;
    end
    else begin
        if ((rst == 0)) begin
            par_out <= 0;
        end
        else if (load) begin
            par_out <= par_in;
        end
    end
end

endmodule
