// File: Register_32bit.v
// Generated by MyHDL 0.11
// Date: Thu Feb  4 19:14:27 2021


`timescale 1ns/10ps

module Register_32bit (
    clk,
    reset,
    load,
    par_in,
    par_out
);


input clk;
input reset;
input load;
input [31:0] par_in;
output [31:0] par_out;
reg [31:0] par_out;




always @(posedge clk, negedge reset) begin: REGISTER_32BIT_SEQ
    if (reset == 0) begin
        par_out <= 0;
    end
    else begin
        if ((reset == 0)) begin
            par_out <= 0;
        end
        else if (load) begin
            par_out <= par_in;
        end
    end
end

endmodule
