// File: decoder_4bit.v
// Generated by MyHDL 0.11
// Date: Wed Feb 10 00:16:48 2021


`timescale 1ns/10ps

module decoder_4bit (
    enable
);


input enable;




always @(enable) begin: DECODER_4BIT_LOGIC
    reg [4-1:0] inpu;
    reg [16-1:0] out;
    if (enable) begin
        if ((inpu == 0)) begin
            out = 0;
        end
        else begin
            out = (2 ** inpu);
        end
    end
    else begin
        out = 0;
    end
end

endmodule
