// File: counter.v
// Generated by MyHDL 0.11
// Date: Wed Feb 10 01:25:22 2021


`timescale 1ns/10ps

module counter (
    enable,
    clk,
    count,
    write_enable,
    write_in
);


input enable;
input clk;
output [11:0] count;
reg [11:0] count;
input write_enable;
input [11:0] write_in;




always @(posedge clk) begin: COUNTER_LOGIC
    if (enable) begin
        if ((count < 4095)) begin
            count <= (count + 1);
        end
        else begin
            count <= 0;
        end
    end
    else begin
        count <= count;
    end
    if (write_enable) begin
        count <= write_in;
    end
end

endmodule
