// File: counter.v
// Generated by MyHDL 0.11
// Date: Sun Feb  7 19:02:05 2021


`timescale 1ns/10ps

module counter (
    enable,
    clk,
    count
);


input enable;
input clk;
output [11:0] count;
reg [11:0] count;




always @(posedge clk) begin: COUNTER_LOGIC
    if (enable) begin
        if ((count < 12)) begin
            count <= (count + 1);
        end
        else begin
            count <= 0;
        end
    end
    else begin
        count <= count;
    end
end

endmodule
