// File: ALU.v
// Generated by MyHDL 0.11
// Date: Thu Feb 11 23:27:02 2021


`timescale 1ns/10ps

module ALU (
    z,
    a,
    b,
    sel
);


output [7:0] z;
reg [7:0] z;
input [7:0] a;
input [7:0] b;
input [3:0] sel;




always @(b, sel, a) begin: ALU_COMBLOGIC
    case (sel)
        'h1: begin
            z = (a + b);
        end
        'h2: begin
            z = (a - b);
        end
        'h3: begin
            z = (a & b);
        end
        'h4: begin
            z = (a | b);
        end
        'h5: begin
            z = (a ^ b);
        end
        default: begin
            z = 0;
        end
    endcase
end

endmodule
